openapi: 3.0.4
info:
  title: Charades Generator
  description: Charades Generator provides random words from curated categories perfect for playing the classic charades acting game.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/charades:
    get:
      summary: Generate Charades Word
      description: Charades Generator provides random words from curated categories perfect for playing the classic charades acting game.
      operationId: charades
      parameters:
      - name: category
        default: all
        in: query
        schema:
          type: string
        required: false
        description: 'Category: all, movies, books, songs, actions, animals, objects'
        example: movies
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  word: Tom Jones
                  category: movies
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
